apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: simple-express-app
  name: simple-express-app
spec:
  ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: simple-express-app
status:
  loadBalancer: {}
